ypeError: Unable to convert function return value to a Python type! The signature was () -> handle
Traceback:
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/home/runner/StockSavvyApp/main.py", line 6, in <module>
    from utils.prediction import get_prediction
File "/home/runner/StockSavvyApp/utils/prediction.py", line 5, in <module>
    from keras.models import Sequential
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/__init__.py", line 3, in <module>
    from keras import __internal__
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/__internal__/__init__.py", line 3, in <module>
    from keras.__internal__ import backend
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/src/__init__.py", line 21, in <module>
    from keras.src import models
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/src/models/__init__.py", line 18, in <module>
    from keras.src.engine.functional import Functional
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/keras/src/engine/functional.py", line 23, in <module>
    import tensorflow.compat.v2 as tf
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
File "/home/runner/StockSavvyApp/.pythonlibs/lib/python3.11/site-packages/tensorflow/python/framework/dtypes.py", line 37, in <module>
    _np_bfloat16 = pywrap_ml_dtypes.bfloat16()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^